require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rspec

inherit_mode:
  merge:
    - Include
    - Exclude

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
      - <%= path.sub(/^!! /, '') %>
    <% end %>

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Layout/EmptyLinesAroundAttributeAccessor: # (0.83)
  Enabled: true

Layout/LineLength:
  Exclude:
    - spec/**/*.rb

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Style/Documentation:
  Exclude:
    - 'spec/**/*'

Naming/PredicateName:
  Exclude:
    - 'lib/faraday/middleware/encode_xml.rb'
